// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2509.Robot2016aMD.subsystems;

import org.usfirst.frc2509.Robot2016aMD.RobotMap;
import org.usfirst.frc2509.Robot2016aMD.commands.*;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    private final SpeedController lMotor = RobotMap.driveTrainlMotor;
    private final SpeedController rMotor = RobotMap.driveTrainrMotor;
    private final edu.wpi.first.wpilibj.RobotDrive robotDrive = RobotMap.robotDrive;
   
    public void initDefaultCommand() {
        
    }
    public void OpControl(Joystick lStick, Joystick rStick){
    	robotDrive.tankDrive(lStick.getY(), rStick.getY());
    }
	public void setSafetyEnabled(boolean b) {
		// TODO Auto-generated method stub
		
	}
}

